### ISSUE TITLE
Add Multiple Engines

### ISSUE THREAD

**Issue by MeNsaaH** [bisoncorps/gophie#1]
The current implementation uses netnaija as the primary source for movies downloads. Other sites that offer movies downloads should be included as well.

We'll need lists of popular *scrapable* sites for movie downloads. Any help would be appreciated

**Comment by MeNsaaH** [comment]
https://www.thelivemirror.com/top-free-movie-download-websites-list/

**Comment by MeNsaaH** [comment]
https://www.goophoneshops.com/free-movie-download-sites/

**Comment by deven96** [comment]
https://fzmovies.net

**Comment by MeNsaaH** [comment]
toxicwap.com

**Comment by MeNsaaH** [comment]
tfpdl.is

**Comment by deven96** [comment]
We should suggest specific engines like #7 as the idea comes up instead of this floating issue
