### ISSUE TITLE
go install error

### ISSUE THREAD

**Issue by stefanwuthrich** [bisoncorps/gophie#19]
➜  ~ go get github.com/bisoncorps/gophie
github.com/bisoncorps/gophie/cmd
go/src/github.com/bisoncorps/gophie/cmd/stream.go:60:4: p.SetStreamURL undefined (type mplayer.Player has no field or method SetStreamURL)

**Comment by MeNsaaH** [comment]
Fixed. My bad. I updated the API and forgot to reflect changes
