### ISSUE TITLE
Colly cannot cache FzMovies

### ISSUE THREAD

**Issue by deven96** [bisoncorps/gophie#6]
FzMovies scraper is slow because we cannot use colly's cache. FzMovies always expires old download keys after a site has been visited so caching will not provide the needed pages to advance to the download link as the old keys used will now be invalid. Find a way to increase scraping speed of FzMovies engine

**Comment by MeNsaaH** [comment]
Maybe it should not be cached then. We should probably add it as a message in verbose mode that FzMovies does not support caching.
